apiVersion: apps/v1
kind: Deployment
metadata:
  name: aline-under-deployment
  labels:
    app: aline-under
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aline-under
  template:
    metadata:
      labels:
        app: aline-under
        role: microservice
    spec:
      containers:
      - name: aline-under-ms
        image: ${AWS_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/underwriter-microservice
        ports:
        - containerPort: 8071
        envFrom:
          - configMapRef:
              name: service-config
          - secretRef:
              name: service-secret
---
apiVersion: v1
kind: Service
metadata:
  name: aline-under-service
spec:
  type: NodePort
  selector:
    app: aline-under
  ports:
    - port: 8071
      targetPort: 8071
      nodePort: 30011