apiVersion: apps/v1
kind: Deployment
metadata:
  name: aline-bank-deployment
  labels:
    app: aline-bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aline-bank
  template:
    metadata:
      labels:
        app: aline-bank
    spec:
      containers:
      - name: aline-bank-ms
        image: ethan1597/aline-bank:latest
        ports:
        - containerPort: 8083
        envFrom:
          - configMapRef:
              name: service-config
          - secretRef:
              name: service-secret
---
apiVersion: v1
kind: Service
metadata:
  name: aline-bank-service
spec:
  type: NodePort
  selector:
    app: aline-bank
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30013