apiVersion: apps/v1
kind: Deployment
metadata:
  name: aline-db-deployment
  labels:
    app: aline-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aline-db
  template:
    metadata:
      labels:
        app: aline-db
    spec:
      containers:
      - name: aline-mysql
        image: ethan1597/aline-db:latest
        ports:
        - containerPort: 3306
        envFrom:
          - secretRef:
              name: db-secret
        volumeMounts:
        - name: aline-db-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: aline-db-storage
        persistentVolumeClaim:
          claimName: aline-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: aline-db-service
spec:
  type: NodePort
  selector:
    app: aline-db
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30007