apiVersion: apps/v1
kind: Deployment
metadata:
  name: aline-user-deployment
  labels:
    app: aline-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aline-user
  template:
    metadata:
      labels:
        app: aline-user
    spec:
      containers:
      - name: aline-user-ms
        image: ethan1597/aline-user:latest
        ports:
        - containerPort: 8070
        env:
        - name: USER_PORT
          valueFrom:
            configMapKeyRef:
              name: service-config
              key: user-port
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: service-config
              key: db-port
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: service-config
              key: db-host
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: service-config
              key: db-name
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: service-secret
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: service-secret
              key: password
        - name: ENCRYPT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: service-secret
              key: encrypt-key
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: service-secret
              key: jwt-key
---
apiVersion: v1
kind: Service
metadata:
  name: aline-user-service
spec:
  type: NodePort
  selector:
    app: aline-user
  ports:
    - port: 8070
      targetPort: 8070
      nodePort: 30010