apiVersion: apps/v1
kind: Deployment
metadata:
  name: aline-db-deployment
  labels:
    app: aline-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aline-db
  template:
    metadata:
      labels:
        app: aline-db
    spec:
      containers:
      - name: aline-mysql
        image: ethan1597/aline-db:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: root-password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: database
---
apiVersion: v1
kind: Service
metadata:
  name: aline-db-service
spec:
  type: NodePort
  selector:
    app: aline-db
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30007