apiVersion: apps/v1
kind: Deployment
metadata:
  name: aline-under-deployment
  labels:
    app: aline-under
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aline-under
  template:
    metadata:
      labels:
        app: aline-under
    spec:
      containers:
      - name: aline-under-ms
        image: ethan1597/aline-under:latest
        ports:
        - containerPort: 8071
        env:
        - name: UNDER_PORT
          valueFrom:
            configMapKeyRef:
              name: service-config
              key: under-port
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: service-config
              key: db-port
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: service-config
              key: db-host
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: service-config
              key: db-name
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: service-secret
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: service-secret
              key: password
        - name: ENCRYPT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: service-secret
              key: encrypt-key
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: service-secret
              key: jwt-key
---
apiVersion: v1
kind: Service
metadata:
  name: aline-under-service
spec:
  type: NodePort
  selector:
    app: aline-under
  ports:
    - port: 8071
      targetPort: 8071
      nodePort: 30011