apiVersion: apps/v1
kind: Deployment
metadata:
  name: aline-bank-deployment
  labels:
    app: aline-bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aline-bank
  template:
    metadata:
      labels:
        app: aline-bank
    spec:
      containers:
      - name: aline-bank-ms
        image: ethan1597/aline-bank:latest
        ports:
        - containerPort: 8083
        env:
        - name: BANK_PORT
          valueFrom:
            configMapKeyRef:
              name: service-config
              key: bank-port
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: service-config
              key: db-port
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: service-config
              key: db-host
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: service-config
              key: db-name
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: service-secret
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: service-secret
              key: password
        - name: ENCRYPT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: service-secret
              key: encrypt-key
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: service-secret
              key: jwt-key
---
apiVersion: v1
kind: Service
metadata:
  name: aline-bank-service
spec:
  type: NodePort
  selector:
    app: aline-bank
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30013