apiVersion: apps/v1
kind: Deployment
metadata:
  name: aline-under-deployment
  namespace: afs-ec
  labels:
    app: aline-under
spec:
  replicas: ${UNDER_REPLICAS}
  selector:
    matchLabels:
      app: aline-under
  template:
    metadata:
      labels:
        app: aline-under
        role: microservice
    spec:
      containers:
      - name: aline-under-ms
        image: ${AWS_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/underwriter-microservice-ec:${COMMIT_HASH}
        ports:
        - name: under-port
          containerPort: 8071
        envFrom:
          - configMapRef:
              name: service-config
          - secretRef:
              name: service-secret
        env:
          - name: APP_PORT
            value: "8071"
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        role: microservice