apiVersion: apps/v1
kind: Deployment
metadata:
  name: aline-trans-deployment
  namespace: afs-ec
  labels:
    app: aline-trans
spec:
  replicas: ${TRANS_REPLICAS}
  selector:
    matchLabels:
      app: aline-trans
  template:
    metadata:
      labels:
        app: aline-trans
        role: microservice
    spec:
      containers:
      - name: aline-trans-ms
        image: ${AWS_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/transaction-microservice-ec:${COMMIT_HASH}
        ports:
        - name: trans-port
          containerPort: 8073
        envFrom:
          - configMapRef:
              name: service-config
          - secretRef:
              name: service-secret
        env:
          - name: APP_PORT
            value: "8073"
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        role: microservice