apiVersion: apps/v1
kind: Deployment
metadata:
  name: aline-user-deployment
  namespace: afs-ec
  labels:
    app: aline-user
spec:
  replicas: ${USER_REPLICAS}
  selector:
    matchLabels:
      app: aline-user
  template:
    metadata:
      labels:
        app: aline-user
        role: microservice
    spec:
      containers:
      - name: aline-user-ms
        image: ${AWS_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/user-microservice-ec:${COMMIT_HASH}
        ports:
        - name: user-port
          containerPort: 8070
        envFrom:
          - configMapRef:
              name: service-config
          - secretRef:
              name: service-secret
        env:
          - name: APP_PORT
            value: "8070"
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        role: microservice