apiVersion: apps/v1
kind: Deployment
metadata:
  name: aline-bank-deployment
  namespace: afs-ec
  labels:
    app: aline-bank
spec:
  replicas: ${BANK_REPLICAS}
  selector:
    matchLabels:
      app: aline-bank
  template:
    metadata:
      labels:
        app: aline-bank
        role: microservice
    spec:
      containers:
      - name: aline-bank-ms
        image: ${AWS_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/bank-microservice-ec:${COMMIT_HASH}
        ports:
        - name: bank-port
          containerPort: 8083
        envFrom:
          - configMapRef:
              name: service-config
          - secretRef:
              name: service-secret
        env:
          - name: APP_PORT
            value: "8083"
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        role: microservice