apiVersion: apps/v1
kind: Deployment
metadata:
  name: aline-gateway-deployment
  namespace: afs-ec
  labels:
    app: aline-gateway
spec:
  replicas: ${GATEWAY_REPLICAS}
  selector:
    matchLabels:
      app: aline-gateway
  template:
    metadata:
      labels:
        app: aline-gateway
    spec:
      containers:
      - name: aline-gateway-container
        image: ${AWS_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/gateway-ec:${COMMIT_HASH}
        ports:
        - containerPort: 8080
        env:
          - name: APP_PORT
            value: "8080"
          - name: APP_SERVICE_HOST
            value: aline-backend-service
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        role: gateway
---
apiVersion: v1
kind: Service
metadata:
  name: aline-gateway-service
  namespace: afs-ec
spec:
  type: NodePort
  selector:
    app: aline-gateway
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30020