apiVersion: apps/v1
kind: Deployment
metadata:
  name: aline-gateway-deployment
  labels:
    app: aline-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aline-gateway
  template:
    metadata:
      labels:
        app: aline-gateway
    spec:
      containers:
      - name: aline-gateway-container
        image: ethan1597/aline-gateway:latest
        ports:
        - containerPort: 8080
        env:
          - name: APP_PORT
            value: "8080"
          - name: APP_SERVICE_HOST
            value: aline-backend-service
---
apiVersion: v1
kind: Service
metadata:
  name: aline-gateway-service
spec:
  type: NodePort
  selector:
    app: aline-gateway
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30020