apiVersion: v1
kind: Service
metadata:
  name: aline-backend-service
spec:
  selector:
    role: microservice
  ports:
    - name: user-backend
      port: 8070
      targetPort: user-port
    - name: under-backend
      port: 8071
      targetPort: under-port
    - name: trans-backend
      port: 8073
      targetPort: trans-port
    - name: bank-backend
      port: 8083
      targetPort: bank-port