apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ec-eks
  region: us-east-2

nodeGroups:
  - name: backend-nodes
    instanceType: t2.medium
    desiredCapacity: 2
    ssh:
      publicKeyName: ec-eks-cluster-key